export const stockStyles = {
    app: { fontFamily: "monospace", fontSize: "11px", color: "#d7e0ea", background: "#0b0f14", minHeight: "100%", padding: "14px", boxSizing: "border-box" },
    header: { display: "flex", justifyContent: "space-between", gap: "12px", alignItems: "flex-start", paddingBottom: "12px", borderBottom: "1px solid #26303b" },
    eyebrow: { fontSize: "10px", letterSpacing: "2px", color: "#6c7f92" },
    title: { fontSize: "23px", fontWeight: 800, color: "#f3f7fb", marginTop: "2px" },
    subtitle: { color: "#8998a8", marginTop: "4px" },
    badges: { display: "flex", flexWrap: "wrap", justifyContent: "flex-end", gap: "5px" },
    badge: { padding: "4px 7px", borderRadius: "4px", fontSize: "10px", fontWeight: 700, border: "1px solid #34404d", background: "#151a20", color: "#9ca9b5" },
    good: { borderColor: "#24543c", background: "#10241b", color: "#8be9b4" },
    warn: { borderColor: "#5f4821", background: "#281f0e", color: "#ffd479" },
    accent: { borderColor: "#285276", background: "#102235", color: "#8ed0ff" },
    heroGrid: { display: "grid", gridTemplateColumns: "repeat(5,minmax(0,1fr))", gap: "7px", margin: "8px 0" },
    hero: { background: "#10161d", border: "1px solid #242f3a", borderRadius: "6px", padding: "9px" },
    heroLabel: { color: "#708090", fontSize: "9px", textTransform: "uppercase", letterSpacing: "0.8px" },
    heroValue: { color: "#f1f5f9", fontSize: "17px", fontWeight: 800, marginTop: "4px", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
    grid: { display: "grid", gridTemplateColumns: "1.55fr 1fr", gap: "7px" },
    card: { background: "#10161d", border: "1px solid #242f3a", borderRadius: "6px", padding: "10px", minWidth: 0 },
    titleRow: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: "8px", marginBottom: "8px" },
    cardTitle: { color: "#91a8bb", fontSize: "10px", fontWeight: 800, letterSpacing: "1px", textTransform: "uppercase" },
    select: { fontFamily: "monospace", color: "#d8e1e9", background: "#0b1117", border: "1px solid #2b3945", borderRadius: "4px", padding: "6px 8px", fontSize: "10px" },
    chartWrap: { height: "300px", position: "relative", background: "#0b1117", border: "1px solid #1b2731", borderRadius: "5px", overflow: "hidden" },
    svg: { width: "100%", height: "100%", display: "block" },
    chartLabel: { position: "absolute", left: "8px", top: "7px", color: "#6f8294", fontSize: "9px" },
    chartLast: { position: "absolute", right: "8px", top: "7px", color: "#dbe5ee", fontSize: "11px", fontWeight: 700 },
    stats: { display: "grid", gridTemplateColumns: "repeat(4,minmax(0,1fr))", gap: "5px", marginTop: "7px" },
    stat: { background: "#0c1218", border: "1px solid #1d2730", borderRadius: "5px", padding: "7px" },
    statLabel: { color: "#69798a", fontSize: "9px", textTransform: "uppercase" },
    statValue: { color: "#e8eef4", fontSize: "11px", marginTop: "3px", fontWeight: 700 },
    table: { marginTop: "2px" },
    row: { display: "grid", gridTemplateColumns: "58px 1fr 1fr 1fr 1fr", gap: "8px", alignItems: "center", padding: "6px 3px", borderBottom: "1px solid #1a232c", fontSize: "10px" },
    rowHead: { color: "#6f8191", textTransform: "uppercase", fontSize: "9px" },
    symbol: { color: "#e4ebf1", fontWeight: 800 },
    right: { textAlign: "right", color: "#a9b8c5" },
    goodText: { color: "#83d8a9", fontWeight: 700 },
    badText: { color: "#ff8f8f", fontWeight: 700 },
    dim: { color: "#8495a5" },
    note: { color: "#94a3b1", fontSize: "10px", lineHeight: 1.45, marginTop: "7px", padding: "7px", background: "#0c1218", borderLeft: "2px solid #35566f" },
    footer: { display: "flex", justifyContent: "space-between", color: "#50606f", fontSize: "9px", paddingTop: "8px" },
};
