export const DEPLOY_FILES = Object.freeze([
    "/hacking/workers/hack.js",
    "/hacking/workers/grow.js",
    "/hacking/workers/weaken.js",
    "/hacking/planner.js",
    "/hacking/tactical-planner.js",
    "/hacking/economy-planner.js",
    "/hacking/economy-targets.js",
    "/hacking/refresh.js",
    "/hacking/telemetry.js",
    "/diagnostics/test-launcher.js",
    "/diagnostics/test.js",
    "/network/root.js",
    "/network/sync.js",
    "/lib/deployment.js",
    "/lib/threads.js",
    "/lib/runtime-state.js",
    "/lib/telemetry.js",
    "/lib/progression.js",
    "/lib/network.js",
    "/lib/targets.js",
    "/lib/state.js",
    "/lib/execution.js",
    "/lib/output.js",
]);

export const DEPLOY_PROBE_FILES = Object.freeze([
    "/hacking/workers/hack.js",
    "/hacking/tactical-planner.js",
    "/lib/runtime-state.js",
]);
