export const styles = {
    app: { fontFamily: "monospace", color: "#d7e0ea", background: "#0b0f14", minHeight: "100%", padding: "13px", boxSizing: "border-box" },
    header: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", padding: "5px 3px 12px", borderBottom: "1px solid #26303b" },
    eyebrow: { fontSize: "9px", letterSpacing: "2px", color: "#6c7f92" },
    title: { fontSize: "21px", fontWeight: 700, color: "#f3f7fb", marginTop: "2px" },
    subtitle: { fontSize: "10px", color: "#8998a8", marginTop: "3px" },
    badges: { display: "flex", gap: "5px", flexWrap: "wrap", justifyContent: "flex-end" },
    badge: { padding: "4px 6px", borderRadius: "4px", fontSize: "9px", fontWeight: 700, border: "1px solid #34404d" },
    badge_good: { color: "#8be9b4", borderColor: "#24543c", background: "#10241b" },
    badge_warn: { color: "#ffd479", borderColor: "#5f4821", background: "#281f0e" },
    badge_accent: { color: "#8ed0ff", borderColor: "#285276", background: "#102235" },
    badge_dim: { color: "#8593a1", background: "#151a20" },
    nav: { display: "flex", gap: "2px", padding: "8px 0" },
    navButton: { fontFamily: "monospace", border: 0, borderBottom: "2px solid transparent", background: "transparent", color: "#728191", padding: "6px 9px", cursor: "pointer", fontSize: "10px" },
    navActive: { color: "#e9f2fa", borderBottom: "2px solid #4fa3dc", background: "#101821" },
    content: { paddingTop: "1px" },
    heroGrid: { display: "grid", gridTemplateColumns: "repeat(4, minmax(0,1fr))", gap: "7px", marginBottom: "7px" },
    heroCard: { background: "#10161d", border: "1px solid #242f3a", borderRadius: "6px", padding: "9px" },
    heroHeaderButton: { width: "100%", display: "flex", justifyContent: "space-between", alignItems: "center", padding: 0, border: 0, background: "transparent", color: "inherit", cursor: "pointer", fontFamily: "monospace" },
    heroLabel: { fontSize: "8px", color: "#708090", letterSpacing: "1px" },
    heroValue: { fontSize: "16px", color: "#f1f5f9", marginTop: "3px", fontWeight: 700, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
    heroSub: { fontSize: "9px", color: "#7d8b99", marginTop: "3px", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
    grid: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0,1fr))", gap: "7px" },
    card: { background: "#10161d", border: "1px solid #242f3a", borderRadius: "6px", padding: "10px", minWidth: 0 },
    wide: { gridColumn: "1 / -1", marginBottom: "7px" },
    cardHeaderButton: { width: "100%", display: "flex", justifyContent: "space-between", alignItems: "center", gap: "8px", padding: 0, marginBottom: "6px", border: 0, background: "transparent", color: "inherit", cursor: "pointer", fontFamily: "monospace", textAlign: "left" },
    cardTitle: { color: "#91a8bb", fontSize: "9px", fontWeight: 700, letterSpacing: "1px", textTransform: "uppercase" },
    collapseGlyph: { color: "#6f8ca2", fontSize: "13px", lineHeight: 1, fontWeight: 700 },
    kv: { display: "flex", justifyContent: "space-between", alignItems: "baseline", gap: "10px", padding: "3px 0", borderBottom: "1px solid #18212a" },
    key: { color: "#758595", fontSize: "9px", flex: "0 0 105px" },
    value: { color: "#d8e1e9", fontSize: "9px", textAlign: "right", overflowWrap: "anywhere" },
    note: { color: "#8796a5", fontSize: "9px", lineHeight: 1.4, marginTop: "6px", padding: "6px", background: "#0c1218", borderLeft: "2px solid #35566f" },
    controlGrid: { display: "grid", gridTemplateColumns: "1fr auto", gap: "12px", alignItems: "center" },
    controlActions: { display: "flex", gap: "5px", flexWrap: "wrap", justifyContent: "flex-end", maxWidth: "600px" },
    compactGrid: { display: "grid", gridTemplateColumns: "repeat(2,minmax(0,1fr))", gap: "0 14px" },
    strategyTitle: { fontSize: "15px", fontWeight: 700, color: "#f0f5fa", marginBottom: "6px" },
    statGrid: { display: "grid", gridTemplateColumns: "repeat(3,minmax(0,1fr))", gap: "5px" },
    stageStrip: { display: "grid", gridTemplateColumns: "repeat(4,minmax(0,1fr))", gap: "5px", marginTop: "7px" },
    stat: { background: "#0c1218", border: "1px solid #1d2730", borderRadius: "5px", padding: "6px" },
    statLabel: { color: "#69798a", fontSize: "8px", textTransform: "uppercase" },
    statValue: { color: "#e8eef4", fontSize: "10px", marginTop: "3px" },
    targetForm: { display: "grid", gridTemplateColumns: "1fr auto auto", gap: "6px" },
    goalForm: { display: "grid", gridTemplateColumns: "1.1fr 1fr auto auto", gap: "6px" },
    multiControlGrid: { display: "grid", gridTemplateColumns: "1.15fr repeat(4,minmax(90px,0.75fr)) auto", gap: "6px", alignItems: "end", marginBottom: "7px" },
    controlField: { display: "flex", flexDirection: "column", gap: "3px", minWidth: 0 },
    controlLabel: { color: "#708090", fontSize: "8px", textTransform: "uppercase", letterSpacing: "0.4px" },
    multiLaunch: { display: "flex", gap: "5px", alignItems: "flex-end", paddingBottom: "1px" },
    multiActivityRows: { marginTop: "7px" },
    multiActivityRow: { display: "grid", gridTemplateColumns: "1.2fr 66px 1fr 1fr 1.35fr", gap: "8px", alignItems: "center", padding: "5px 3px", borderBottom: "1px solid #1a232c", fontSize: "9px" },
    multiTargetName: { color: "#dbe5ee", fontWeight: 700, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
    input: { minWidth: 0, fontFamily: "monospace", color: "#d8e1e9", background: "#0b1117", border: "1px solid #2b3945", borderRadius: "4px", padding: "6px 7px", fontSize: "9px" },
    primaryButton: { fontFamily: "monospace", padding: "6px 8px", borderRadius: "4px", border: "1px solid #2e5c7d", background: "#12304a", color: "#bfe4ff", cursor: "pointer", whiteSpace: "nowrap", fontSize: "9px" },
    clearButton: { fontFamily: "monospace", padding: "6px 8px", borderRadius: "4px", border: "1px solid #5b4930", background: "#271e11", color: "#f0cf91", cursor: "pointer", whiteSpace: "nowrap", fontSize: "9px" },
    disabledButton: { opacity: 0.45, cursor: "default" },
    goalStatus: { color: "#9dc7e4", fontSize: "9px", marginTop: "5px" },
    progressTrack: { height: "5px", borderRadius: "5px", background: "#1a232c", overflow: "hidden", margin: "5px 0" },
    progressFill: { height: "100%", background: "#438ab8" },
    targetRow: { display: "grid", gridTemplateColumns: "34px 1.4fr 70px 110px 100px", gap: "7px", padding: "5px 3px", borderBottom: "1px solid #1a232c", fontSize: "9px" },
    prepRow: { display: "grid", gridTemplateColumns: "1.45fr 80px 82px 88px 90px", gap: "8px", alignItems: "center", padding: "5px 3px", borderBottom: "1px solid #1a232c", fontSize: "9px" },
    hostRow: { display: "grid", gridTemplateColumns: "1.5fr 1fr 1fr", gap: "8px", padding: "5px 3px", borderBottom: "1px solid #1a232c", fontSize: "9px" },
    rank: { color: "#5e88a6" },
    right: { textAlign: "right", color: "#9aabba" },
    workerRow: { display: "grid", gridTemplateColumns: "1.5fr 1fr 55px 100px", gap: "8px", padding: "5px 3px", borderBottom: "1px solid #1a232c", fontSize: "9px" },
    dimText: { color: "#8495a5", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
    goodText: { color: "#83d8a9", fontSize: "9px", fontWeight: 700 },
    warnText: { color: "#ffd479", fontSize: "9px", fontWeight: 700 },
    pipelineRows: { marginTop: "6px" },
    timeline: { marginTop: "8px" },
    timelineRow: { display: "grid", gridTemplateColumns: "28px 1fr 62px", gap: "7px", alignItems: "center", margin: "6px 0" },
    timelineLabel: { color: "#dbe5ee", fontWeight: 700, fontSize: "9px" },
    timelineTrack: { position: "relative", height: "14px" },
    timelineBaseline: { position: "absolute", left: 0, right: 0, top: "6px", height: "2px", background: "#24303b" },
    timelineMarkerPlanned: { position: "absolute", top: "2px", width: "8px", height: "8px", marginLeft: "-5px", borderRadius: "50%", border: "2px solid #8ed0ff", background: "#10161d" },
    timelineMarkerActual: { position: "absolute", top: "4px", width: "8px", height: "8px", marginLeft: "-4px", borderRadius: "50%", background: "#ffd479" },
    timelineError: { color: "#9fb0bf", fontSize: "8px", textAlign: "right" },
    details: { marginTop: "7px", borderTop: "1px solid #1d2832", paddingTop: "5px" },
    summary: { cursor: "pointer", color: "#8ea5b8", fontSize: "9px" },
    command: { marginTop: "7px" },
    commandLabel: { color: "#708090", fontSize: "8px", marginBottom: "2px" },
    code: { color: "#b8d6e8", background: "#0b1117", border: "1px solid #1d2832", borderRadius: "4px", padding: "4px 6px", fontSize: "8px" },
    footer: { display: "flex", justifyContent: "space-between", color: "#50606f", fontSize: "8px", padding: "8px 2px 0" },
};
